"""added image/pdf field in topic table

Revision ID: 1a6e1125aeca
Revises: b0eaf0066d91
Create Date: 2023-01-29 21:01:12.614189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6e1125aeca'
down_revision = 'b0eaf0066d91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('image_pdf_string', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'image_pdf_string')
    # ### end Alembic commands ###
